#!/bin/sh
set -e
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/Pacifica /usr/share/icons/Pacifica-U
fi
# End automatically added section
